routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth'], function (){

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('files', 'FilesController')->only(['index', 'create', 'store', 'destroy']);
});

Route::post('download/{file}', 'FilesController@download')->name('file.download');
Route::get('{file}', 'FilesController@show')->name('file.show');

app/Models/File.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    protected $fillable = [
        'file_name',
        'user_id',
        'extension',
        'path',
        'token',
        'total_download'
    ];
    
    public function getRouteKeyName()
    {
        return  'token';
    }
}

app/User.php
<?php

namespace App;

use App\Models\File;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function files()
    {
        $this->hasMany(File::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a Dashboard page
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('dashboard.index');
    }
}

app/Http/Controllers/FilesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\FileUploadRequest;
use \App\Models\File;

class FilesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $files = File::where('user_id', auth()->user()->id)->orderBy('id', 'DESC')->get();
        
        return view('files.index', compact('files'));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('files.add');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(FileUploadRequest $request)
    {
        if($request->hasFile('file')) {
            $file = $request->file('file');
            $filename = $file->getClientOriginalName();
            $extension = $file->getClientOriginalExtension();
            
            $path = \Storage::put('files', $file);
            
            
            File::create([
                'file_name' => $filename,
                'user_id' => auth()->user()->id,
                'extension' => $extension,
                'path' => $path,
                'token' => uniqid() . time(),
            ]);
            
            return redirect()->route('files.index')->with('message', __('message.file.add'));
        }
        
        return redirect()->back();
    }
    
    /**
     * Display the specified resource.
     *
     * @param File $file
     * @return \Illuminate\View\View
     */
    public function show(File $file)
    {
        if ($file) {
            return view('files.show', compact('file'));
        }
        
        abort(404);
    }
    
    /**
     * Download the specified resource.
     *
     * @param File $file
     * @return \Symfony\Component\HttpFoundation\BinaryFileResponse
     */
    public function download(File $file)
    {
        if ($file) {
            $file->increment('total_download');
            
            return response()->download(storage_path('app/public/' . $file->path), $file->file_name);
        }
        
        abort(404);
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    
    public function destroy($id)
    {
        $file = File::where([
            'id' => $id,
            'user_id' => auth()->user()->id
        ])->first();
        
        if ($file) {
            \Storage::delete($file->path);
            $file->delete();
            
            return redirect()->route('files.index')->with('message', __('message.file.delete'));
        }
        
        return redirect()->route('files.index')->with('error', __('message.error'));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest');
    }

    /**
     * Display a Home page
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-6">
            <div class="jumbotron">
                <h1 class="display-4">{{config('app.name')}}</h1>
                <p class="lead">Please click on upload file button to start sharing your files.</p>
                <hr class="my-4">
                <p class="lead">
                    <a href="{{route('files.create')}}" class="btn btn-lg btn-primary">Upload file</a>
                </p>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/files/add.blade.php
@extends('layouts.app')

@section('content')
    @include('message')
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-6">
                <div class="form-wrapper mt-5">
                    <h1 class="display-6">File Upload</h1>

                    <hr class="my-4">
                    <form method="POST" action="{{route('files.store')}}" enctype="multipart/form-data">
                        {!! csrf_field() !!}
                        <div class="form-group">
                            <input type="file" class="form-control-file" name="file" id="file">
                            @if($errors->has('file'))
                                <span class="text-danger">{{$errors->first('file')}}</span>
                            @endif
                        </div>
                        <button class="btn btn-lg btn-primary" type="submit" value="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/files/index.blade.php
@extends('layouts.app')

@section('content')
    @include('message')
    <div class="container">
        <div class="mt-5">
            <div class="row">
                <div class="offset-md-2 col-md-8">
                    <a class="btn btn-sm btn-primary mb-3" href="{{route('files.create')}}"> Upload File</a>
                </div>
                <div class="col-md-8 mx-auto">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Created At</th>
                            <th>Total Download</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($files->isNotEmpty())
                            @foreach($files as $key => $item)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$item->file_name}}</td>
                                    <td>{{\Carbon\Carbon::parse($item->created_at)->format('d, M Y')}}</td>
                                    <td>{{$item->total_download}}</td>
                                    <td>
                                        <a class="btn btn-sm btn-primary d-inline-block btn-show-modal" href="javascript:void(0);" data-url="{{route('file.show', $item->token)}}" >share</a>
                                        <a class="btn btn-sm btn-danger d-inline-block btn-delete" href="javascript:void(0);" data-url="{{route('files.destroy', $item->id)}}">Delete</a>
                                        <form method="POST" action="{{route('files.destroy', $item->id)}}">
                                            {!! method_field('delete')  !!}
                                            {!! csrf_field() !!}
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="5" class="text-center">No data found...</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

    @include('modals.share_modal')
    @include('modals.delete_modal')
@endsection

resources/views/files/show.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="mt-5">
            <div class="row">
                <div class="card mx-auto" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{$file->file_name}}</h5>
                        <p class="card-text">{{\Carbon\Carbon::parse($file->created_at)->format('M d, Y')}}</p>
                        <form  method="POST" action="{{route('file.download', $file->token)}}">
                            {!! csrf_field() !!}
                            <button class="btn btn-primary" type="submit">Download</button>
                        </form>

                    </div>
                </div>

            </div>
        </div>

    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center align-items-center section">
        <div class="col-6">
            <div class="jumbotron">
                <h1 class="display-4">{{ config('app.name', 'Laravel') }}</h1>
                <p class="lead">This is test application shows how easily we can upload file and sharing it with outer world.</p>
                <hr class="my-4">
                <p>In order to use this application either login or register in this demo application.</p>
                <p class="lead">
                    <a href="{{ route('login') }}" class="btn btn-lg btn-primary">{{ __('Login') }}</a>
                    <a href="{{ route('register') }}" class="btn btn-lg btn-primary">{{ __('Register') }}</a>
                </p>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
@extends('layouts.master')

@section('navbar')
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ route('dashboard') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{route('files.index')}}">My files</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
@endsection

@section('content')
    @yield('content')
@endsection

resources/views/layouts/auth.blade.php
@extends('layouts.master')

@section('navbar')
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>
@endsection

@section('content')
    @yield('content')
@endsection

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    @yield('navbar')

    <main>
        @yield('content')
    </main>
</div>
@yield('script')
</body>
</html>

resources/views/message.blade.php
@if(\Session::has('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {!! \Session::get('error') !!}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif
@if(\Session::has('message'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {!! \Session::get('message') !!}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/modals/delete_modal.blade.php
<div id="delete_modal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Are you sure want to delete ?</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form method="POST" action="">
                    {!! method_field('delete')  !!}
                    {!! csrf_field() !!}
                    <button type="submit" class="btn btn-danger">Yes</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                </form>
            </div>
        </div>

    </div>
</div>

resources/views/modals/share_modal.blade.php
<div id="share_modal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">File Share</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">

                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="file_share_link" placeholder="File share" aria-label="File share" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="copy_share_link">Copy</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>